### ISSUE TITLE
Error trying to load gamemode

### ISSUE THREAD

**Issue by nocwed** [feedblackg44/ash#1]
After the 7/7 update this appears when the gamemode tries to load 

L 07/14/2022 - 23:21:22: [SM] Exception reported: Failed to create native "ASH_IsSaxtonHaleModeMap", name is probably already in use
L 07/14/2022 - 23:21:22: [SM] Blaming: ASH_Core.smx
L 07/14/2022 - 23:21:22: [SM] Call stack trace:
L 07/14/2022 - 23:21:22: [SM]   [0] CreateNative
L 07/14/2022 - 23:21:22: [SM]   [1] Line 27, ASH/API.sp::API_MakeGeneralNatives
L 07/14/2022 - 23:21:22: [SM]   [2] Line 44, ASH/API.sp::API_MakeNatives
L 07/14/2022 - 23:21:22: [SM]   [3] Line 3, ASH/API.sp::API_Init
L 07/14/2022 - 23:21:22: [SM]   [4] Line 1101, ASH_Core.sp::AskPluginLoad2
[SM] Plugin ASH_Core.smx failed to load: unexpected error 23 in AskPluginLoad callback.

**Comment by NITROYUASH** [comment]
Have you installed the ASH plugin twice?
